### ISSUE TITLE
Request from mantainer of nrjavaserial

### ISSUE THREAD

**Issue by jirkapinkas** [crea-doo/nrjavaserial-rfc2217#1]
Hello, on my website where's your project available for download Kevin Harrington posted this message:

+ I maintain nrjavaserial and would accept a Pull Request through Github to add these features to avoid a fork.

Note: this is just friendly repost :-) Link: http://javalibs.com/artifact/at.crea-doo.util.nrjavaserial/nrjavaserial-rfc2217

**Comment by crea-doo** [comment]
The artifact I provide is no fork at all - so no worries ;-)

It just depends on NRJavaSerial and at runtime both libraries (NRJavaSerial and the RFC2217 extension) have to be loaded to work properly.

If the RFC2217 support is of interest for you and you want to add that directly we can also talk about that, but it would introduce some new dependencies to your project...

(Also posted this answer to http://javalibs.com/artifact/at.crea-doo.util.nrjavaserial/nrjavaserial-rfc2217)

**Comment by madhephaestus** [comment]
i'm ok with that, id like to have a nice and easy to use library for everyone to use without having to hunt for it. If you send a PR with the integrations i can add it, and if you want i can make you a contributor on the core project.

**Comment by crea-doo** [comment]
Sounds good. I'll prepare a PR in the next days...

**Comment by crea-doo** [comment]
Created PR under https://github.com/NeuronRobotics/nrjavaserial/pull/34
